In [14]:
%load_ext autoreload
%autoreload 2

import numpy as np
import jax.numpy as jnp
import jax
import jax.random as rnd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
n_samples = 100
n_electrons = 4
re = np.random.normal(0., 1., (n_samples, n_electrons, 3))

@jax.jit
def function(re, n_samples=100, n_electrons=4):
    re1 = jnp.expand_dims(re, axis=2)
    re2 = jnp.transpose(re1, [0, 2, 1, 3])
    ee_vectors = re1 - re2
    mask = jnp.expand_dims(jnp.expand_dims(jnp.eye(re.shape[1], dtype=bool), axis=0), axis=-1)
    return ee_vectors[mask]


z = function(re)
grad1f = jax.grad(function)
g1 = gradf(x)
grad2f = jax.grad(gradf)
g2 = grad2f(x)

primal, tangent = jax.jvp(grad_f_closure, (x,), (eye[..., i],))

IndexError: Array boolean indices must be concrete.

In [ ]:
float(e_mean)

In [40]:
import numpy as np
import jax.numpy as jnp
import jax
import jax.random as rnd
from jax import lax

# def _body_fun(i, val):
#             # primal is the first order evaluation
#             # tangent is the second order
#             primal, tangent = jax.jvp(grad_f_closure, (x,), (eye[..., i],))
#             return val + primal[i]**2 + tangent[i]
    
#         # from lower to upper
#         # (lower, upper, func(int, a) -> a, init_val)
#         # this is like functools.reduce()
#         # val is the previous  val (initialised to 0.0)
#         return -0.5 * lax.fori_loop(0, n, _body_fun, 0.0)

    
key = rnd.PRNGKey(1)
n = 25
x = rnd.normal(key, (n,))

# def function(x):
#     x = x.reshape((5, 5))
#     n = x.shape[0]
#     eye = jnp.eye(n, dtype=bool)
#     y = x[eye]
#     return jnp.sum(y)

# z = jax.jit(function)(x)


def function(x):
    x = x.reshape((5, 5))
    n = x.shape[0]
    y = jnp.diag(x)
    print(y.shape)
    return jnp.sum(y)

z = jax.jit(function)(x)

def function(x):
    x = x.reshape((5, 5))
    n = x.shape[0]
    def _reduce(x):
        eye = jnp.eye(n, dtype=bool)
        y = x[eye]
        return y
    return jnp.sum(_reduce(x))

z = jax.jit(function)(x)


# grad1f = jax.grad(function)
# g1 = grad1f(x)
# grad2f = jax.grad(lambda x: jnp.sum(grad1f(x)))

# def body_fun(i, val):
#     eye = jnp.eye(n)
#     primal, tangent = jax.jvp(grad2f, (x,), (eye[i],))
#     return tangent
    
# lax.fori_loop(0, n, body_fun, 0.0)

(5,)


IndexError: Array boolean indices must be concrete.

In [71]:
# def create_upper_triangle(x):
    # x: (m, n, 3)
x = np.random.normal(0., 1., (n_samples, n_electrons, 3))
x_split = jnp.split(x, x.shape[1], axis=1)
x_splits = [jnp.split(x, [i], axis=1)[1] for i in range(1, n_electrons)]
result = jnp.concatenate([tmp1 - tmp2 for (tmp1, tmp2) in zip(x_split, x_splits)], axis=1)
print(result.shape)

(100, 6, 3)


In [50]:
for z in x_splits:
    print(z.shape)
    
print(x_split[0].shape)
x_split[0] - x_splits[0]
for r in result:
    print(r.shape)

(100, 3, 3)
(100, 2, 3)
(100, 1, 3)
(100, 1, 3)
(100, 3, 3)
(100, 2, 3)
(100, 1, 3)


In [52]:
print(result.shape)

(100, 6, 3)


In [78]:
n = 4
square = np.random.normal(0., 1., (n, n))
def get_upper_triangle(square):
    n = square.shape[0]

    split1 = jnp.split(square, n, axis=0)
    split2 = [jnp.split(split1[i], [i], axis=1)[1] for i in range(0, n)]
    result = jnp.concatenate(split2, axis=1)
    print(square)
    print(result.shape)
    print(result)
    
jax.jit(get_upper_triangle)

get_upper_triangle(square)

[[-0.15805753  1.65397532 -0.37937143  1.24986335]
 [-1.06852586 -0.54313048 -0.06912744 -0.97227058]
 [-0.30623977 -0.18439201 -1.08056399 -0.65101704]
 [-0.86658695 -0.68066002  0.49506929  0.99775595]]
(1, 10)
[[-0.15805753  1.6539754  -0.37937143  1.2498634  -0.54313046 -0.06912744
  -0.97227055 -1.080564   -0.65101707  0.99775594]]


In [68]:
for s in split1:
    print(s)

[[-0.9713497  1.7841934 -2.5548215  0.388427 ]]
[[0.7867979  0.18127199 0.5735382  0.5045947 ]]
[[-0.6850107   0.33981436  0.8401847   0.99845684]]
[[ 0.04265355 -0.9178238   2.4606369   0.327196  ]]


In [79]:
jnp.split(s, [1], axis=1)[0,1]

TypeError: list indices must be integers or slices, not tuple

In [92]:
n = 4
square = np.random.normal(0., 1., (n, n))
def drop_diagonal(square):
    n = square.shape[0]
    split1 = jnp.split(square, n, axis=0)
    upper = [jnp.split(split1[i], [j], axis=1)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=1)[0] for i, j in zip(range(0, n), range(0, n))]
    upper.extend(lower)
    result = jnp.concatenate(upper, axis=1)
    return result
    print(square)
    print(result.shape)
    print(result)
    
jit_drop = jax.jit(drop_diagonal)

def time(n):
    square = jnp.array(np.random.normal(0., 1., (n, n)))
    %timeit drop_diagonal(square)
    %timeit jit_drop(square)

for i in [4, 8, 16, 32, 64, 128, 256, 512]:
    print(i)
    time(i)




4
1.47 ms ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
35.5 µs ± 387 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
8
2.93 ms ± 7.16 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35.7 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
16
6.04 ms ± 48.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
37 µs ± 1.45 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
32
12.3 ms ± 368 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
39.4 µs ± 1.42 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
64
29.4 ms ± 874 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
53.2 µs ± 19.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
128
50.3 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
74.5 µs ± 27.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
256
104 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
49.9 µs ± 6.98 µs per loop (mean ± std. dev. of 7 runs, 

In [96]:
square = jnp.array(np.random.normal(0., 1., (m, n, n)))
split1 = jnp.split(square, n, axis=1)
print(split1[0].shape)

(1024, 1, 4)


In [135]:

def drop_diagonal(square):
    n = square.shape[1]
    split1 = jnp.split(square, n, axis=1)
    upper = [jnp.split(split1[i], [j], axis=2)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=2)[0] for i, j in zip(range(1, n), range(1, n))]
    arr = [ls[i] for i in range(n-1) for ls in (upper, lower)]
    result = jnp.concatenate(arr, axis=2)
    return result

jit_drop = jax.jit(drop_diagonal)

def time(n, m=1024):
    square = jnp.array(np.random.normal(0., 1., (m, n, n)))
    %timeit drop_diagonal(square).block_until_ready()
    %timeit jit_drop(square).block_until_ready()

for i in [4, 8, 16, 32, 64, 128, 256, 512]:
    print('\n', i)
    time(i)


 4
1.43 ms ± 53.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
40.5 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 8
2.99 ms ± 28.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
40.4 µs ± 281 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 16
6.49 ms ± 162 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
55.5 µs ± 4.11 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 32
12.9 ms ± 333 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
186 µs ± 29.2 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

 64
30.3 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
851 µs ± 8.15 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

 128
51.8 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.23 ms ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

 256
110 ms ± 3.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5.29 ms ± 20.4 µs per loop (mean ± std. dev. of 7 run

In [101]:
def time(n, m=512):
    square = jnp.array(np.random.normal(0., 1., (m, n, n)))
    %timeit drop_diagonal(square).block_until_ready()
    %timeit jit_drop(square).block_until_ready()

for i in [4, 8, 16, 32, 64, 128, 256, 512]:
    print('\n', i)
    time(i)


 4
1.56 ms ± 72.2 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
40.4 µs ± 778 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 8
3.05 ms ± 65.5 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
40.1 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 16
6.57 ms ± 323 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
43.1 µs ± 606 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 32
13 ms ± 382 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
87.8 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

 64
26.4 ms ± 656 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
481 µs ± 9.31 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

 128
53.6 ms ± 1.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.41 ms ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

 256
115 ms ± 4.08 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.4 ms ± 66.3 µs per loop (mean ± std. dev. of 7 runs, 1 

In [112]:
def drop_diagonal(square):
    n = square.shape[1]
    split1 = jnp.split(square, n, axis=1)
    upper = [jnp.split(split1[i], [j], axis=2)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=2)[0] for i, j in zip(range(0, n), range(0, n))]
    upper.extend(lower)
    result = jnp.concatenate(upper, axis=2)
    return result
    print(square)
    print(result.shape)
    print(result)

m, n = 512, 5
square = jnp.array(np.random.normal(0., 1., (m, n, n)))
r1 = drop_diagonal(square)
eye = ~np.eye(n, dtype=bool).reshape(1, n, n).repeat(m, axis=0)
r2 = square[eye].reshape(m, 1, 20)
print(r1.shape, r2.shape)
print(jnp.sum(jnp.abs(r1 - r2)))

(512, 1, 20) (512, 1, 20)


In [115]:
def drop_diagonal(square):
    n = square.shape[1]
    split1 = jnp.split(square, n, axis=1)
    upper = [jnp.split(split1[i], [j], axis=2)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=2)[0] for i, j in zip(range(0, n), range(0, n))]
    lower.extend(upper)
    result = jnp.concatenate(lower, axis=2)
    return result
    print(square)
    print(result.shape)
    print(result)

m, n = 512, 5
square = jnp.array(np.random.normal(0., 1., (m, n, n)))
r1 = drop_diagonal(square)
eye = ~np.eye(n, dtype=bool).reshape(1, n, n).repeat(m, axis=0)
r2 = square[eye].reshape(m, 1, 20)
print(r1.shape, r2.shape)
print(jnp.sum(jnp.abs(r1 - r2)))

(512, 1, 20) (512, 1, 20)
11545.75


In [117]:
def drop_diagonal(square):
    n = square.shape[2]
    split1 = jnp.split(square, n, axis=2)
    upper = [jnp.split(split1[i], [j], axis=1)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=1)[0] for i, j in zip(range(0, n), range(0, n))]
    upper.extend(lower)
    result = jnp.concatenate(upper, axis=1)
    return result
    print(square)
    print(result.shape)
    print(result)

m, n = 512, 5
square = jnp.array(np.random.normal(0., 1., (m, n, n)))
r1 = drop_diagonal(square)
eye = ~np.eye(n, dtype=bool).reshape(1, n, n).repeat(m, axis=0)
r2 = square[eye].reshape(m, 20, 1)
print(r1.shape, r2.shape)
print(jnp.sum(jnp.abs(r1 - r2)))

(512, 20, 1) (512, 20, 1)
11569.146


In [118]:
def drop_diagonal(square):
    n = square.shape[2]
    split1 = jnp.split(square, n, axis=2)
    upper = [jnp.split(split1[i], [j], axis=1)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=1)[0] for i, j in zip(range(0, n), range(0, n))]
    lower.extend(upper)
    result = jnp.concatenate(lower, axis=1)
    return result
    print(square)
    print(result.shape)
    print(result)

m, n = 512, 5
square = jnp.array(np.random.normal(0., 1., (m, n, n)))
r1 = drop_diagonal(square)
eye = ~np.eye(n, dtype=bool).reshape(1, n, n).repeat(m, axis=0)
r2 = square[eye].reshape(m, 20, 1)
print(r1.shape, r2.shape)
print(jnp.sum(jnp.abs(r1 - r2)))

(512, 20, 1) (512, 20, 1)
8181.157


In [16]:
# drop diag of m x n x n x f
import jax.numpy as jnp
import numpy as np
def drop_diagonal(square):
    n = square.shape[1]
    split1 = jnp.split(square, n, axis=1)
    upper = [jnp.split(split1[i], [j], axis=2)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=2)[0] for i, j in zip(range(1, n), range(1, n))]
    arr = [ls[i] for i in range(n-1) for ls in (upper, lower)]
    result = jnp.concatenate(arr, axis=2)
    return jnp.squeeze(result)

m, n, f = 512, 5, 10
square = jnp.array(np.random.normal(0., 1., (m, n, n, f)))
r1 = drop_diagonal(square)
mask = jnp.expand_dims(~jnp.eye(n, dtype=bool), axis=(0, 3))
mask = jnp.repeat(jnp.repeat(mask, m, axis=0), f, axis=-1)
r2 = square[mask]
r2 = r2.reshape((m, n ** 2 - n, f))
print(r1.shape, r2.shape)
print(jnp.sum(jnp.abs(r1 - r2)))
# for i, j in zip(r1[0], r2):
#     print('\n')
#     print(i, j)
r1 - r2

(512, 20, 10) (512, 20, 10)
0.0


DeviceArray([[[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             ...,

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0.,

In [ ]:

def drop_diagonal(square):
    n = square.shape[1]
    split1 = jnp.split(square, n, axis=0)
    upper = [jnp.split(split1[i], [j], axis=1)[1] for i, j in zip(range(0, n), range(1, n))]
    lower = [jnp.split(split1[i], [j], axis=1)[0] for i, j in zip(range(1, n), range(1, n))]
    print(len(upper), len(lower))
    print(lower)
    arr = [ls[i] for i in range(n-1) for ls in (upper, lower)]
    result = jnp.concatenate(arr, axis=1)
    return result
    print(square)
    print(result.shape)
    print(result)
    
m, n = 512, 5
square = jnp.array(np.random.normal(0., 1., (n, n)))
r1 = drop_diagonal(square)
eye = ~np.eye(n, dtype=bool)
r2 = square[eye]
print(r1.shape, r2.shape)
print(jnp.sum(jnp.abs(r1 - r2)))
print(square)
print(r1)
print(r2)
for i, j in zip(r1[0], r2):
    print('\n')
    print(i, j)